version: "3.8"

services:
  web:
    build:
      context: .
      target: deps
    command: ["deno", "run", "--allow-net", "--allow-read", "--watch", "dev"]
    volumes:
      - .:/app
    environment:
      - HOST=0.0.0.0
      - PORT=4321
      - DENO_ENV=development
    restart: unless-stopped

  prod:
    build:
      context: .
      target: runtime
    environment:
      - HOST=0.0.0.0
      - PORT=4321
      - DENO_ENV=production
    restart: unless-stopped
    profiles:
      - prod
